server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 5 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      max-lifetime: 1765060  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      pool-name: outapi-pool
  application:
    name: outapi-nacos-config
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: user_mmr
      password: 123456
      #虚拟host 可以不设置,使用server默认host
      #virtual-host: JCcccHost
      publisher-returns: true  #开启发送失败返回。。确认消息已发送到队列
      publisher-confirms: true  #开启确认发送。。确认消息已发送交换机
      listener:
        simple:
          acknowledge-mode: manual #开启ACK

# ========MP配置 无需配置mybatis了===========
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
 # config-location: classpath:mapper/mybatis-config.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.vp.example.*.entity
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      #驼峰下划线转换
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'